Repository team-TEN-TEN/EatMatJib-Server, pull requests merged in 2024-09, with the labels that each got.

#11 [feat] 사용자 정보 API
  src/main/java/com/tenten/eatmatjib/common/config/auth/AuthUserResolver.java
  src/main/java/com/tenten/eatmatjib/common/config/auth/JwtUtil.java
  src/main/java/com/tenten/eatmatjib/common/exception/ErrorCode.java
  src/main/java/com/tenten/eatmatjib/member/controller/MemberController.java
  src/main/java/com/tenten/eatmatjib/member/controller/response/InfoMemberRes.java
  src/main/java/com/tenten/eatmatjib/member/service/MemberInfoService.java
  src/test/java/com/tenten/eatmatjib/member/controller/MemberControllerTest.java
  src/test/java/com/tenten/eatmatjib/member/service/MemberInfoServiceTest.java
Labels: feature

#14 [feat] 사용자 설정 업데이트 API
  build.gradle
  src/main/java/com/tenten/eatmatjib/common/config/CoordinateConverterConfig.java
  src/main/java/com/tenten/eatmatjib/common/util/CoordinateConverter.java
  src/main/java/com/tenten/eatmatjib/member/controller/MemberController.java
  src/main/java/com/tenten/eatmatjib/member/controller/request/UpdateMemberReq.java
  src/main/java/com/tenten/eatmatjib/member/controller/response/UpdateMemberRes.java
  src/main/java/com/tenten/eatmatjib/member/domain/Coord.java
  src/main/java/com/tenten/eatmatjib/member/domain/Member.java
  src/main/java/com/tenten/eatmatjib/member/service/MemberUpdateService.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/com/tenten/eatmatjib/member/controller/MemberControllerTest.java
  src/test/java/com/tenten/eatmatjib/member/service/MemberUpdateServiceTest.java
Labels: feature

#15 [feat] 맛집 목록 API
  src/main/java/com/tenten/eatmatjib/common/config/QueryDslConfig.java
  src/main/java/com/tenten/eatmatjib/common/exception/ErrorCode.java
  src/main/java/com/tenten/eatmatjib/common/util/CoordinateConverter.java
  src/main/java/com/tenten/eatmatjib/member/domain/Coord.java
  src/main/java/com/tenten/eatmatjib/restaurant/controller/RestaurantController.java
  src/main/java/com/tenten/eatmatjib/restaurant/controller/response/RestaurantsQueryRes.java
  src/main/java/com/tenten/eatmatjib/restaurant/domain/FilterType.java
  src/main/java/com/tenten/eatmatjib/restaurant/domain/OrderType.java
  src/main/java/com/tenten/eatmatjib/restaurant/domain/RangeType.java
  src/main/java/com/tenten/eatmatjib/restaurant/domain/Restaurant.java
  src/main/java/com/tenten/eatmatjib/restaurant/repository/RestaurantRepository.java
  src/main/java/com/tenten/eatmatjib/restaurant/repository/custom/RestaurantCustomRepository.java
  src/main/java/com/tenten/eatmatjib/restaurant/repository/custom/RestaurantCustomRepositoryImpl.java
  src/main/java/com/tenten/eatmatjib/restaurant/service/RestaurantQueryService.java
  src/main/java/com/tenten/eatmatjib/restaurant/service/command/RestaurantSearchCondition.java
  src/main/resources/db/migration/V1__init.sql
  src/test/java/com/tenten/eatmatjib/restaurant/controller/RestaurantControllerTest.java
  src/test/java/com/tenten/eatmatjib/restaurant/repository/custom/RestaurantCustomRepositoryTest.java
  src/test/java/com/tenten/eatmatjib/restaurant/service/RestaurantQueryServiceTest.java
Labels: feature

#18 #1 [chore] 멤버, 음식점, 리뷰 dummy data 생성
  .github/CODEOWNERS
  src/main/resources/data.sql
  src/test/java/com/tenten/eatmatjib/common/util/CoordinateConverterTest.java
Labels: feature

#21 #20 [feat] 시군구 데이터 목록 조회 API 구현
  src/main/java/com/tenten/eatmatjib/region/controller/RegionController.java
  src/main/java/com/tenten/eatmatjib/region/controller/dto/RegionRes.java
  src/main/java/com/tenten/eatmatjib/region/service/RegionQueryService.java
  src/test/java/com/tenten/eatmatjib/region/controller/RegionControllerTest.java
Labels: feature

#16 [feat] 음식점 상세 API
  build.gradle
  src/main/java/com/tenten/eatmatjib/common/config/CoordinateConverterConfig.java
  src/main/java/com/tenten/eatmatjib/common/config/SecurityConfig.java
  src/main/java/com/tenten/eatmatjib/common/exception/BusinessException.java
  src/main/java/com/tenten/eatmatjib/common/exception/ErrorCode.java
  src/main/java/com/tenten/eatmatjib/common/exception/ErrorResponse.java
  src/main/java/com/tenten/eatmatjib/common/exception/GlobalExceptionHandler.java
  src/main/java/com/tenten/eatmatjib/common/util/CoordinateConverter.java
  src/main/java/com/tenten/eatmatjib/common/util/RandomCodeUtil.java
  src/main/java/com/tenten/eatmatjib/member/controller/MemberController.java
  src/main/java/com/tenten/eatmatjib/member/domain/Member.java
  src/main/java/com/tenten/eatmatjib/restaurant/controller/RestaurantController.java
  src/main/java/com/tenten/eatmatjib/restaurant/domain/Restaurant.java
  src/main/java/com/tenten/eatmatjib/restaurant/dto/RestaurantQueryRes.java
  src/main/java/com/tenten/eatmatjib/restaurant/service/RestaurantQueryService.java
  src/main/java/com/tenten/eatmatjib/review/domain/Review.java
  src/main/java/com/tenten/eatmatjib/review/repository/ReviewRepository.java
  src/test/java/com/tenten/eatmatjib/member/controller/MemberControllerTest.java
  src/test/java/com/tenten/eatmatjib/member/service/MemberLoginServiceTest.java
  src/test/java/com/tenten/eatmatjib/member/service/MemberRegisterServiceTest.java
  src/test/java/com/tenten/eatmatjib/restaurant/controller/RestaurantControllerTest.java
  src/test/java/com/tenten/eatmatjib/restaurant/controller/RestaurantDetailControllerTest.java
  src/test/java/com/tenten/eatmatjib/restaurant/service/RestaurantQueryServiceTest.java
Labels: feature

#17 [feat] 음식점 리뷰 생성 API
  .idea/codeStyles/codeStyleConfig.xml
  src/main/java/com/tenten/eatmatjib/common/exception/ErrorCode.java
  src/main/java/com/tenten/eatmatjib/member/domain/Coord.java
  src/main/java/com/tenten/eatmatjib/restaurant/domain/Restaurant.java
  src/main/java/com/tenten/eatmatjib/review/controller/ReviewController.java
  src/main/java/com/tenten/eatmatjib/review/dto/ReviewRequest.java
  src/main/java/com/tenten/eatmatjib/review/repository/ReviewRepository.java
  src/main/java/com/tenten/eatmatjib/review/service/AddReviewService.java
  src/test/java/com/tenten/eatmatjib/member/controller/MemberControllerTest.java
  src/test/java/com/tenten/eatmatjib/restaurant/service/RestaurantQueryServiceTest.java
  src/test/java/com/tenten/eatmatjib/restaurant/service/RestaurantsQueryServiceTest.java
  src/test/java/com/tenten/eatmatjib/review/controller/ReviewControllerTest.java
  src/test/java/com/tenten/eatmatjib/review/service/AddReviewServiceTest.java
Labels: feature

#22 #3 [fix] 리뷰 컨트롤러 테스트 실패 에러 해결
  src/main/java/com/tenten/eatmatjib/review/dto/ReviewRequest.java
  src/test/java/com/tenten/eatmatjib/review/controller/ReviewControllerTest.java
Labels: bug

#24 [doc] README 작성
  README.md
Labels: documentation
